### ISSUE TITLE
BUG found on execution of SummTriver example

### ISSUE THREAD

**Issue by JohnRojas** [creat89/SummTriver#1] opened 2019-01-15 15:07 UTC
A bug is identified at the following command execution:
- perl SummTriver_src\summTriver_Exp.perl Example\example.xml

The output of this command is:

![1](https://user-images.githubusercontent.com/17374097/51189364-831e9200-18a5-11e9-8711-1e0960376f51.PNG)

**Comment by creat89** [comment] 2019-01-15 15:22
I have separates both issues, to work on them separately. I'll check this issue ASAP.

**Comment by creat89** [comment] 2019-01-15 19:23
Hello @JohnRojas , I have cloned the repository and tested it in Linux, but I cannot reproduce the bug. I have tried to break the code in line 204 in SummTriver_Exp.perl:

```perl
%{$param{PR}}=map{$_->{system} => $_->{path}} $set->findnodes('./PR/file');
```

Or to generate a similar error, but still nothing. Can you post your example.xml file please?

**Comment by JohnRojas** [comment] 2019-01-15 19:43
Hello @creat89 
I have the following XML file:

![imagen](https://user-images.githubusercontent.com/17374097/51204842-27b2cb00-18ca-11e9-89ba-5ed6929925fc.png)

I replaced the absolute paths of each document or directory. However, I'm not sure if at line 27 is only the directory, or needs to be executed on Linux (This example was executed on Windows)

Regards

**Comment by creat89** [comment] 2019-01-15 19:47
As the paths are for Windows, you might need to escape the backslashes (\) and use double backslashes (\\) instead. For example, "C:\\Users \\areyes\\Desktop..."

Could you check that?

If that's the problem, I'll indicate it in the Wiki.

**Comment by JohnRojas** [comment] 2019-01-15 20:08
I tried to execute with double backslash, but I have the same output

![imagen](https://user-images.githubusercontent.com/17374097/51206906-f092e880-18ce-11e9-992a-ed8b97f52552.png)

**Comment by creat89** [comment] 2019-01-21 14:06
Hi @JohnRojas , I've been trying to replicate the bug, but still no success. Can you paste your XML in a gist (https://gist.github.com/) and share the link. In this way I can check your XML file. 

As well, are you using the last version of the code? Otherwise the line 204 of your code is not the same to the one that I'm using.

**Comment by creat89** [comment] 2019-03-24 19:01
Hello @JohnRojas, I don't know if you continue having problems running SummTriver. I have created a Docker image of SummTriver which might make easier to use SummTriver. Because of this, I'm closing this issue.

**Closed as completed by creat89** 2019-03-24 19:01 UTC
Labels: question
